
language: ruby

cache: bundler

rvm:
  - 2.5.1

dist: trusty

services:
  - postgresql

before_script:
  - bundle
  - bundle exec rails db:create
  - bundle exec rails db:migrate RAILS_ENV=test
  - curl -L https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz | tar xz


test:
  adapter: postgresql
  database: travis_ci_test

script:
  - bundle exec rspec


after_success:
  - coveralls

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
